# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


laura = User.create!(:email => "laura@lehtori.com", :first_name => "Laura", :last_name => "Lehtori", :password => "salasana", :teacher => true)
teemu = User.create!(:email => "teemu@tuutori.com", :first_name => "Teemu", :last_name => "Tuutori", :password => "salasana", :teacher => true)
aatu = User.create!(:email =>  "aatu@auttavainen.com", :first_name => "Aatu", :last_name => "Auttavainen", :password => "salasana", :teacher => true)

hanna = User.create!(:email =>  "hanna@hakija.com", :first_name => "Hanna", :last_name => "Hakija", :password => "salasana", :teacher => false)
onni = User.create!(:email =>  "onni@oppija.com", :first_name => "Onni", :last_name => "Oppija", :password => "salasana", :teacher => false)
katariina = User.create!(:email =>  "katariina@kiinnostunut.com", :first_name => "Katariina", :last_name => "Kiinnostunut", :password => "salasana", :teacher => false)

Subject.find_or_create_by!(name:"matematiikka", detail:"ala-aste")
Subject.find_or_create_by!(name:"matematiikka", detail:"ylä-aste")
Subject.find_or_create_by!(name:"matematiikka", detail:"ylä-aste")
Subject.find_or_create_by!(name:"matematiikka", detail:"lukio")
Subject.find_or_create_by!(name:"matematiikka", detail:"yliopisto")
Subject.find_or_create_by!(name:"äidinkieli", detail:"ala-aste")
Subject.find_or_create_by!(name:"äidinkieli", detail:"ylä-aste")
Subject.find_or_create_by!(name:"äidinkieli", detail:"lukio")
Subject.find_or_create_by!(name:"englanti", detail:"ala-aste")
Subject.find_or_create_by!(name:"englanti", detail:"ylä-aste")
Subject.find_or_create_by!(name:"englanti", detail:"lukio")
Subject.find_or_create_by!(name:"englanti", detail:"yliopisto")
Subject.find_or_create_by!(name:"ranska", detail:"ala-aste")
Subject.find_or_create_by!(name:"ranska", detail:"ylä-aste")
Subject.find_or_create_by!(name:"ranska", detail:"lukio")
Subject.find_or_create_by!(name:"ranska", detail:"yliopisto")
Subject.find_or_create_by!(name:"ruotsi", detail:"ala-aste")
Subject.find_or_create_by!(name:"ruotsi", detail:"ylä-aste")
Subject.find_or_create_by!(name:"ruotsi", detail:"lukio")
Subject.find_or_create_by!(name:"ruotsi", detail:"yliopisto")
Subject.find_or_create_by!(name:"fysiikka", detail:"ala-aste")
Subject.find_or_create_by!(name:"fysiikka", detail:"ylä-aste")
Subject.find_or_create_by!(name:"fysiikka", detail:"lukio")
Subject.find_or_create_by!(name:"fysiikka", detail:"yliopisto")
Subject.find_or_create_by!(name:"kemia", detail:"ala-aste")
Subject.find_or_create_by!(name:"kemia", detail:"ylä-aste")
Subject.find_or_create_by!(name:"kemia", detail:"lukio")
Subject.find_or_create_by!(name:"kemia", detail:"yliopisto")
Subject.find_or_create_by!(name:"biologia", detail:"ala-aste")
Subject.find_or_create_by!(name:"biologia", detail:"ylä-aste")
Subject.find_or_create_by!(name:"biologia", detail:"lukio")
Subject.find_or_create_by!(name:"biologia", detail:"yliopisto")
Subject.find_or_create_by!(name:"maantieto", detail:"ala-aste")
Subject.find_or_create_by!(name:"maantieto", detail:"ylä-aste")
Subject.find_or_create_by!(name:"maantieto", detail:"lukio")
Subject.find_or_create_by!(name:"maantieto", detail:"yliopisto")
Subject.find_or_create_by!(name:"uskonto", detail:"ala-aste")
Subject.find_or_create_by!(name:"uskonto", detail:"ylä-aste")
Subject.find_or_create_by!(name:"uskonto", detail:"lukio")
Subject.find_or_create_by!(name:"uskonto", detail:"yliopisto")
Subject.find_or_create_by!(name:"yhteiskuntaoppi", detail:"ala-aste")
Subject.find_or_create_by!(name:"yhteiskuntaoppi", detail:"ylä-aste")
Subject.find_or_create_by!(name:"yhteiskuntaoppi", detail:"lukio")
Subject.find_or_create_by!(name:"yhteiskuntaoppi", detail:"yliopisto")
Subject.find_or_create_by!(name:"historia", detail:"ala-aste")
Subject.find_or_create_by!(name:"historia", detail:"ylä-aste")
Subject.find_or_create_by!(name:"historia", detail:"lukio")
Subject.find_or_create_by!(name:"historia", detail:"yliopisto")
Subject.find_or_create_by!(name:"filosofia", detail:"ala-aste")
Subject.find_or_create_by!(name:"filosofia", detail:"ylä-aste")
Subject.find_or_create_by!(name:"filosofia", detail:"lukio")
Subject.find_or_create_by!(name:"filosofia", detail:"yliopisto")
Subject.find_or_create_by!(name:"espanja", detail:"ala-aste")
Subject.find_or_create_by!(name:"espanja", detail:"ylä-aste")
Subject.find_or_create_by!(name:"espanja", detail:"lukio")
Subject.find_or_create_by!(name:"espanja", detail:"yliopisto")
Subject.find_or_create_by!(name:"venäjä", detail:"ala-aste")
Subject.find_or_create_by!(name:"venäjä", detail:"ylä-aste")
Subject.find_or_create_by!(name:"venäjä", detail:"lukio")
Subject.find_or_create_by!(name:"venäjä", detail:"yliopisto")
Subject.find_or_create_by!(name:"italia", detail:"ala-aste")
Subject.find_or_create_by!(name:"italia", detail:"ylä-aste")
Subject.find_or_create_by!(name:"italia", detail:"lukio")
Subject.find_or_create_by!(name:"italia", detail:"yliopisto")
Subject.find_or_create_by!(name:"latina", detail:"ala-aste")
Subject.find_or_create_by!(name:"latina", detail:"ylä-aste")
Subject.find_or_create_by!(name:"latina", detail:"lukio")
Subject.find_or_create_by!(name:"latina", detail:"yliopisto")
Subject.find_or_create_by!(name:"kiina", detail:"ala-aste")
Subject.find_or_create_by!(name:"kiina", detail:"ylä-aste")
Subject.find_or_create_by!(name:"kiina", detail:"lukio")
Subject.find_or_create_by!(name:"kiina", detail:"yliopisto")
Subject.find_or_create_by!(name:"japani", detail:"ala-aste")
Subject.find_or_create_by!(name:"japani", detail:"ylä-aste")
Subject.find_or_create_by!(name:"japani", detail:"lukio")
Subject.find_or_create_by!(name:"japani", detail:"yliopisto")
Subject.find_or_create_by!(name:"farmasia", detail:"pääsykoe")
Subject.find_or_create_by!(name:"kasvatustiede", detail:"pääsykoe")
Subject.find_or_create_by!(name:"kauppatieteet", detail:"pääsykoe")
Subject.find_or_create_by!(name:"maataloustiede", detail:"pääsykoe")
Subject.find_or_create_by!(name:"oikeustiede", detail:"pääsykoe")
Subject.find_or_create_by!(name:"psykologia", detail:"pääsykoe")
Subject.find_or_create_by!(name:"valtiotiede", detail:"pääsykoe")
Subject.find_or_create_by!(name:"lääketiede", detail:"pääsykoe")
Subject.find_or_create_by!(name:"eläinlääketiede", detail:"pääsykoe")
Subject.find_or_create_by!(name:"viestintä", detail:"pääsykoe")
Subject.find_or_create_by!(name:"tekniikka", detail:"pääsykoe")
